"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['NewsletterApp.py']
APP_NAME = "NewsletterApp"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'icon.ico',
    'plist': {
        'LSUIElement': True,
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "NewsletterApp",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2023, Esteban Madrigal, All Rights Reserved",
        'NSAppleEventsUsageDescription': 'We need access to Outlook to send and open the newsletters.',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
